### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by faizananwerali** [steventheworker/Dock-Expos--home#1]
Thank you for this awesome product.

This is my request that you please keep this product free forever and maintain this project for a longer period

**Comment by steventheworker** [comment]
My dock apps will always be free (I think this feature should just come with macOS already). I primarily use Dock Exposé now anyways (over DockAltTab) so rest assured that it will regularly be maintained. But for the time being, I am shifting my focus back to improving DockAltTab seeing as Exposé has outpaced it feature-wise.

Once that game of catch-up is complete, a feature I'd like to add to Dock Exposé very soon is closing, minimizing, & maximizing (full screen) windows when you click on their red, yellow, and green buttons in their preview.
