### ISSUE TITLE
Does not seem to work on Mac OS 12.6.1?

### ISSUE THREAD

**Issue by arooni** [steventheworker/Dock-Expos--home#10]
Installed via github 2.9.2, added appropriate permissions in accessibility settings and it is running, and I *am getting previews* but I'm seeing little previews above the app, not the cool filtering of what app is running full screen as shown in the demo video.  I'm running Alt Tab and Contexts simultaneously; could that be messing things up?

**Comment by steventheworker** [comment]
Sorry for the dealyed response, but none of the windows in the demo are fullscreen. If the window is fullscreen App Exposé cannot and will not show them. You can test this by right clicking the dock icon and clicking "Show All Windows". 

However, after seeing this issue,, this was really easily added into DockAltTab. Version 2.7 will be ready in 1-3 days. Will post another comment when it is ready.

**Comment by arooni** [comment]
Thanks for writing.  I should have been more precise.  It's rather it seems in your demo  (https://dockexpose.netlify.app/) that as you mouse over different apps it seems to show all the associated windows from that app.  That's what I meant to say versus full screen windows.

I seem to get small previews of the windows of an application and then to see them on a bigger basis I have to mouse to the individual window screens first vs how your demo does it (mousing over ann app seems to pull up the associated windows for each app.  I can take video if my words are terrible in explaining which i fear they are

**Comment by steventheworker** [comment]
I think one of the permissions isn't applying. Probably "Input Monitoring", or Accessibility.

1. quit the app
2. remove permissions with: ```tccutil reset All com.steventheworker.Dock-Expose``` (paste in terminal)
3. re-add both permissions in Settings
4. run the app

I also think you're describing the minimized window / recent files area? https://youtu.be/hMvcUK_FZFA
