### ISSUE TITLE
How to restore menubar icon?

### ISSUE THREAD

**Issue by seanbperiod** [steventheworker/Dock-Expos--home#14]
I think I ticked the setting to hide the menubar icon, but I want to change some settings and I'm not sure how. 

Any way to restore this? Thanks

**Comment by steventheworker** [comment]
You can use activity monitor to kill DockAltTab and then the icon shows up (doesn't remember you checked it)

same as [this DockAltTab issue](https://github.com/steventheworker/DockAltTab/issues/12)

**Comment by steventheworker** [comment]
Fixed in v3.00.0
