### ISSUE TITLE
reopen windows when logging back in

### ISSUE THREAD

**Issue by georgiartakov** [steventheworker/Dock-Expos--home#18]
Hi mate, 

i love AltTab and Dock Expose so thanks for the great applications.

I just upgraded my Mac to Ventura 13.5 an Dock Expose stopped working.

I checked permissions, turned them off and on again. Tried reinstalling Dock Expose. Nothing seems to work.

Can you please check this out?

**Comment by georgiartakov** [comment]
Ok update... i found a fix. I had to manually close all the apps that were running. You can just right click and close them on the dock. For Finder i went to Activity Control and closed it there. So it's not a big issue. After i closed all the Apps, Dock Expose started working like before. You can close the issue if you want, or leave it here if somebody else has the same problem.

**Comment by steventheworker** [comment]
Updating performs a restart as if the "reopen windows when logging back in" checkbox was checked, which causes the same issue. Pretty sure clicking the menubar option "Kill/Restart Dock" remedies this as well.

**Comment by georgiartakov** [comment]
Hi mate, i tried "Kill/Restart Dock" but it didn't help me in that certain situation. I had to close the windows manually like mentioned before. Where can i find the "reopen windows when logging back in" checkbox? I have a german interface and i cannot seem to find it in the settings.

**Comment by steventheworker** [comment]
I was referring to this dialog window's checkbox, it comes up when you click log out / shut down / restart.
<img width="423" alt="image" src="https://github.com/steventheworker/Dock-Expos--home/assets/43100895/e5a7fee8-ed9c-4dc3-ba63-756d4454b425">
