### ISSUE TITLE
Dock Expose needs accessibility permissions

### ISSUE THREAD

**Issue by alumni** [steventheworker/Dock-Expos--home#23]
Since upgrading to v3 I keep being asked to grant accessibility permissions. This is granted, but somehow it is not detected.

**Comment by steventheworker** [comment]
Make sure Dock Exposé isn't running when you run this terminal command to remove all entries from all permission groups in settings: 
```tccutil reset All com.steventheworker.Dock-Expose```

Now start Dock Exposé and giving it permissions should work.

**Comment by alumni** [comment]
Thanks, that did it :)
