### ISSUE TITLE
App doesn't register that Accessibility permissions have been enabled

### ISSUE THREAD

**Issue by spiritually-soup** [steventheworker/Dock-Expos--home#28]
MacOS Monterey 12.7.2
Attempting to install latest release

![Screen Recording 480p](https://github.com/steventheworker/Dock-Expos--home/assets/92115028/9727e14e-eb70-4f84-9444-0adb153624e8)

**Comment by steventheworker** [comment]
Sometimes you need to remove all the permissions before they will register.

Make sure you quit the app, then run the following command.
```tccutil reset All com.steventheworker.Dock-Expose```

This will remove all the entries labeled "Dock Exposé" in Settings (or you can do it manually).

**Comment by spiritually-soup** [comment]
It worked - tysm!
