### ISSUE TITLE
Expose closes as soon mouse cursor is moved away from dock icon

### ISSUE THREAD

**Issue by tomsjansons** [steventheworker/Dock-Expos--home#4]
Apologies if this is not the right way of asking for help! 

I think your app has great potential but it does not seem to work for me...

It seems that the Expose almost never stays open after I move the mouse. It opens and shows all windows when hovering on the dock icon but closes immediately after I move the mouse and I'm unable to click on any of the expose windows to actually switch 

You can see the behaviour here https://www.loom.com/share/201d65ce97dd4386aa80bbd6777d58c7

Am I missing something? Is there some additional install step I needed to do?

An interesting thing I've discovered is that Expose will stay open if I have a window minimised but only while I have the mouse on the bottom of the Expose screen where the minimised windows are shown, as soon as I move away to click on an Expose window, Expose closes...

Here this can be seen in action https://www.loom.com/share/fc2fc21b5d714939989aacb463926e0c

Any help resolving this issue would be greatly appreciated!

**Comment by steventheworker** [comment]
Thanks for opening this issue. I able to reproduce after plugging in a external monitor (doesn't seem to happen on my air's primary monitor). Will release an update soon!

**Comment by steventheworker** [comment]
Please try v2.91
https://github.com/steventheworker/Dock-Expos--home/releases/download/v2.91/DockExposev2.91.zip

**Comment by tomsjansons** [comment]
thank you very much for jumping on this so quickly! 
So the latest version 2.9.1 does nothing for me - does not trigger Expose no matter what I do.
This is my current monitor setup (I sometimes work with my laptop open, sometimes closed)
<img width="668" alt="image" src="https://user-images.githubusercontent.com/1428917/198851077-6a13a43d-b2e6-459f-8161-866bfe4449ae.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1428917/198851079-7a038d3b-57d4-4435-b4c6-597e33ca73cd.png">


or

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1428917/198851087-3bfd7429-dea5-44d5-aed0-7de0c4b0027d.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1428917/198851093-847983c1-4047-4624-8a43-fe391d91057d.png">


But the odd thing is - I went back to version 2.9 and now suddenly it works perfectly! not sure what changed though, I may have switched monitors around and changed which monitor is the main one... But anyways, it works and I am super happy! :) 

Let me know if I can help with debugging or any additional details!

**Comment by steventheworker** [comment]
Just letting you know monitor support is bare bones because the M1 air only supports 1 external screen. Will update this thread when I have a version that works with 3+ monitors so you/someone can test it.

**Comment by tomsjansons** [comment]
As I said earlier - I am on version 2.9 and it works perfectly with 2 external displays and the internal MacBook one.
You can see here https://www.loom.com/share/48013af4b4a44d50b015dfdd52261da8
The Expose shows as expected and everything works perfectly! 
Still not sure what happened and why it did not work for me before...
So I'm going to close this issue as all is good for me :)
