### ISSUE TITLE
[Bug Report] Chaotic Preferences in Dock Exposé v2.9.2

### ISSUE THREAD

**Issue by Maghsad** [steventheworker/Dock-Expos--home#7]
Hi, 

Dock Exposé v2.9.2 preferences pallet seems so messy. Could you please fix this issue?

**Also, it seems the useful red and yellow buttons are added to Dock Exposé, which is a great feature. Unfortunately, they are not displayed in practice. It's a great feature, and I am very hopeful to see it.**

<img src="https://i.ibb.co/MS6W5Q3/SCR-20221121-f1j.png" alt="SCR-20221121-f1j" border="0" />

**Comment by steventheworker** [comment]
Will fix the transparency on the Restart Dock and Reduce Motion buttons. But don't think I should remove them. I'll give the UI a quick polish for the update with the updates checkbox.

Maybe the note at the bottom can be a tooltip when hovering the "Restart Dock" button.

The Red Yellow checkbox is a placeholder for a tentative feature. I might hide it.

**Comment by Maghsad** [comment]
I acknowledge the Restart Dock and Reduce Motion buttons are essential in this pallet. The only concern was the transparency issues. I'm so excited to see the version that the red and yellow buttons work.

**Comment by steventheworker** [comment]
Okay v2.92 has been patched, let me know what you think.
