### ISSUE TITLE
[Bug Report][v2.9.2] Red and Yellow (Close and Minimize) Buttons in Dock Exposé 

### ISSUE THREAD

**Issue by Maghsad** [steventheworker/Dock-Expos--home#8]
Hi @steventheworker,

Thanks again for developing the useful Dock Exposé. It seems the red and yellow (close and minimize) buttons are added to Dock Exposé v2.9.9. It is a great feature that makes Dock Exposé much more practical. Unfortunately, these buttons are not displayed in practice. Could you please fix this bug?

<img src="https://i.ibb.co/rZ9kvxB/SCR-20221121-ft8.png"/>

**Comment by steventheworker** [comment]
v3.0 will not be released until the "Enable Red Yellow" checkbox works in some form, but it's in early development so I might just hide it in a dev branch until close enough. Until then Dock Exposé versions will be in the v2.9's.

**Comment by Maghsad** [comment]
Thanks again @steventheworker for your prompt response as well as all your efforts in developing and improving this great and useful app.
