### ISSUE TITLE
requested setting - increase mouseout delay

### ISSUE THREAD

**Issue by kroyster** [steventheworker/Dock-Expos--home#9]
With multiple monitors, I often have a lot of screen to traverse between mousing over the dock icon and then selecting the desired application preview instance that pops up, sometimes on a separate monitor.    I'm struggling to get there fast enough before the mouseout event causes the preview windows to disappear.  Can a delay be added, perhaps configurable in the settings?

**Comment by steventheworker** [comment]
This is technically already implemented. It's hardcoded to close after 1.5 seconds (single monitor), but if the mouse moved to a different monitor, it will add +1.5 more seconds before it will close. So if the delay seems much quicker than 3 seconds, it could be a bug.

You can try to resolve it by swapping the primary monitor, or changing screen arrangements.
<details>
  <summary>Code in question that makes me suspect that bug fix...</summary>

```               
if ((dT < 1.5 || prevPID == dockPID) && extendedOffsetX) {
    if ((x >= primaryScreenWidth && lastMouseLocation.x <= primaryScreenWidth) || (x <= primaryScreenWidth && lastMouseLocation.x >= primaryScreenWidth)) {
        forceProceed = YES;
    }
}
```
</details>

If messing with this works, yet it's still too fast, report back and I'll make it configurable when I push the fix. I should also mention, developing on my M1 limits my testing to 1 external monitor max, so Dock Exposé currently only supports 2 displays.

**Comment by kroyster** [comment]
I have 3 external monitors, in addition to the main laptop screen, so maybe that is part of the problem?  I'm seeing the previews close almost immediately if I slow-drag my mouse from the dock towards the previews - definitely much quicker than 1.5 seconds.  I'll have to play with my monitor configuration later and get back with you.  Thanks for following up!

**Comment by steventheworker** [comment]
Yeah that's definitely that's what's causing this, it's 2 screens maximum, and that includes the internal laptop screen.

My apps bind to monitors in a very rudimentary way (eg: [DockAltTab](https://github.com/steventheworker/DockAltTab/blob/main/DockAltTab/AppDelegate.m#L400), [screenhook](https://github.com/steventheworker/screenhook/blob/main/screenhook/AppDelegate.m#L118)). 

The plan is to fix this in screenhook first, then copy into Dock Exposé and DockAltTab once it's working properly.

**Comment by steventheworker** [comment]
oh yeah I think it works now
